name       : ftjam
version    : 2.5.2
release    : 3
source     :
    - http://sourceforge.net/projects/freetype/files/ftjam/2.5.2/ftjam-2.5.2.tar.gz/download : a5d456f65477d77936e1726f5f803a2e6def18a6c6fccf5ea8528926c136abc8
license    : custom
summary    : FT Jam - an enhanced version of the Jam build tool
component  : programming.tools
description: |
    FT Jam - an enhanced version of the Jam build tool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
